#!/bin/bash

source ${HOME}/sites/vhs/.env

export NODE_ENV=development
export ROOT_DIR=$(git rev-parse --show-toplevel)

echo "DISPLAY: [$DISPLAY]"
echo "DB_USER: [$DB_USER]"
echo "DB_NAME: [$DB_NAME]"
echo "DB_HOST: [$DB_HOST]"
echo "DB_PORT: [$PGPORT]"
echo "DATABASE_URL: [$DATABASE_URL]"
echo "PGUSER: [$PGUSER]"
echo "PGDATABASE: [$PGDATABASE]"    
echo "PGHOST: [$PGHOST]"
echo "PGPORT: [$PGPORT]"
echo "NODE_ENV: [$NODE_ENV]"
echo "COMPOSE_BAKE: [$COMPOSE_BAKE]"
echo "ROOT_DIR: [$ROOT_DIR]"
echo "PATH: [$PATH]"
echo "USERPW: [$USERPW]"

echo "PGPASSWORD: [$PGPASSWORD]"
echo "DB_PASSWORD: [$DB_PASSWORD]"