services:
  nginx:
    image: nginx:alpine
    container_name: dev-vhs-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    build:
      context: ./nginx
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production  

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./nginx/certbot/conf:/etc/letsencrypt
  #     - ./nginx/certbot/www:/var/www/certbot

  db:
    image: postgres:latest
    container_name: dev-vhs-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=vhsdb
      - NODE_ENV=production  
    ports:
      - "5432:5432"
    volumes:
      - vhsdb_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      args:
        - NODE_ENV=production

    container_name: dev-vhs-backend
    environment:
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: vhsdb
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: postgres://admin:admin123@db:5432/vhsdb
      PGUSER: admin
      PGPASSWORD: admin123
      PGDATABASE: vhsdb
      PGHOST: db
      PGPORT: 5432
      NODE_ENV: production
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - app-network
    volumes:
      - ./backend/blocked_news_words.txt:/app/blocked_news_words.txt:ro

  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
    container_name: dev-vhs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend_next_cache:/app/.next
    command: npm run dev
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=development

volumes:
  vhsdb_data:
  frontend_next_cache:

networks:
  app-network:
    driver: bridge
