services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vhsdb
    ports:
      - "5432:5432"
    volumes:
      - vhsdb_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/vhsdb
    depends_on:
      - db

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"

volumes:
  vhsdb_data:
