services:
  nginx:
    image: nginx:alpine
    container_name: vhs-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./nginx/certbot/conf:/etc/letsencrypt
  #     - ./nginx/certbot/www:/var/www/certbot

  db:
    image: postgres:latest
    container_name: vhs-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vhsdb
    volumes:
      - vhsdb_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: vhs-backend
    environment:
      DATABASE_URL: postgres://user:password@db:5432/vhsdb
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: vhs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  vhsdb_data:

networks:
  app-network:
    driver: bridge
