#!/bin/bash
export DISPLAY=:0
export DB_USER=admin
export DB_NAME=vhsdb
export DB_HOST=db
export DB_PORT=5432
export DATABASE_URL=postgres://admin:admin123@db:5432/vhsdb
export PGUSER=admin
export PGDATABASE=vhsdb
export PGHOST=db
export PGPORT=5432
export NODE_ENV=
export COMPOSE_BAKE=true
export ROOT_DIR=$(git rev-parse --show-toplevel)
export PATH=${ROOT_DIR}/utils:$PATH

export PGPASSWORD=`cat ${ROOT_DIR}/.adminpw`
export DB_PASSWORD=`cat ${ROOT_DIR}/.adminpw`

# Check system information and set conda environment accordingly
if uname -a | grep -q ":jwbox"; then
    source /home/jw/miniforge3/etc/profile.d/conda.sh
    echo "Setting conda environment to 'vhs'"
    conda activate vhs
elif uname -a | grep -q "Ubuntu"; then
    echo "Setting conda environment to 'base'"
    source /home/jw/miniforge3/etc/profile.d/conda.sh
    conda activate base
fi