-- 040_create_player_cards_table.sql

CREATE TABLE player_cards (
  id SERIAL PRIMARY KEY,
  player_id INTEGER NOT NULL,
  play_date DATE NOT NULL,
  course_id INTEGER NOT NULL,
  differential NUMERIC,
  hcpi NUMERIC,
  hcp NUMERIC,
  gross INTEGER,
  net INTEGER,
  tarj VARCHAR(10),
  verified BOOLEAN DEFAULT false,
  weather VARCHAR(255),
  day_of_week VARCHAR(20),
  category VARCHAR(50),
  post TEXT,
  judges TEXT,
  ida INTEGER,
  vta INTEGER,
  bir VARCHAR(50),
  par_holes VARCHAR(50),
  bog INTEGER,
  bg2 INTEGER,
  bg3g INTEGER,
  plus_bg3 VARCHAR(50),
  putts VARCHAR(50),
  tee_id INTEGER,
  h01 INTEGER,
  h02 INTEGER,
  h03 INTEGER,
  h04 INTEGER,
  h05 INTEGER,
  h06 INTEGER,
  h07 INTEGER,
  h08 INTEGER,
  h09 INTEGER,
  h10 INTEGER,
  h11 INTEGER,
  h12 INTEGER,
  h13 INTEGER,
  h14 INTEGER,
  h15 INTEGER,
  h16 INTEGER,
  h17 INTEGER,
  h18 INTEGER
); 