#!/bin/bash
cd ${ROOT_DIR}
clear

SERVICES=""

# Process command line arguments
if [[ $# -gt 0 ]]; then
  for arg in "$@"; do
    case $arg in
      --db)
        SERVICES="$SERVICES db"
        ;;
      --frontend)
        SERVICES="$SERVICES frontend"
        ;;
      --backend)
        SERVICES="$SERVICES backend"
        ;;
      --nginx)
        SERVICES="$SERVICES nginx"
        ;;
    esac
  done
fi

# Execute docker compose logs command
if [[ -n "$SERVICES" ]]; then
  docker compose -f ${ROOT_DIR}/docker-compose.yml logs -f $SERVICES
else
  docker compose -f ${ROOT_DIR}/docker-compose.yml logs -f
fi 


# # Replace <container> with your container name or ID

# # Method 1: find + truncate
# docker exec <container> sh -c \
#   "find /var/log -type f -name '*.log' -exec truncate -s 0 {} +"

# # Method 2: shell redirection loop
# docker exec <container> sh -c \
#   'for f in /var/log/**/*.log /var/log/*.log; do
#      [ -f "$f" ] && : > "$f"
#    done'
